// <auto-generated />
using System;
using MediumApi.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MediumApi.Migrations
{
    [DbContext(typeof(MediumContext))]
    [Migration("20210210075453_InitialWithSeed")]
    partial class InitialWithSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("MediumApi.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f35b48d-cb87-4783-bfdb-21e36012930a"),
                            Description = "There are should be text consist of lorem ipsum",
                            Title = "Let's build several projects"
                        },
                        new
                        {
                            Id = new Guid("bffcf83a-0224-4a7c-a278-5aae00a02c1e"),
                            Description = "Hello world, second chance to get a chance",
                            Title = "Sort of"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
